# Generated by Django 5.2.16 on 2026-07-30 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task_type', models.CharField(choices=[('FULL', '全量'), ('INCREMENTAL', '增量')], default='INCREMENTAL', max_length=20, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('PENDING', '待执行'), ('RUNNING', '执行中'), ('PAUSED', '已暂停'), ('SUCCESS', '成功'), ('FAILED', '失败'), ('CANCELLED', '已取消')], default='PENDING', max_length=20, verbose_name='状态')),
                ('requested_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='计划采集条数')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('last_checkpoint', models.JSONField(blank=True, default=dict, verbose_name='最近检查点')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='成功数')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='跳过数')),
                ('failure_count', models.PositiveIntegerField(default=0, verbose_name='失败数')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('source_target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_tasks', to='sources.sourcetarget', verbose_name='采集入口')),
            ],
            options={
                'verbose_name': '采集任务',
                'verbose_name_plural': '采集任务',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CollectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.PositiveIntegerField(verbose_name='运行序号')),
                ('status', models.CharField(choices=[('PENDING', '待执行'), ('RUNNING', '执行中'), ('PAUSED', '已暂停'), ('SUCCESS', '成功'), ('FAILED', '失败'), ('CANCELLED', '已取消')], max_length=20, verbose_name='状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='成功数')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='跳过数')),
                ('failure_count', models.PositiveIntegerField(default=0, verbose_name='失败数')),
                ('checkpoint_json', models.JSONField(blank=True, default=dict, verbose_name='检查点')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='collection.collectiontask', verbose_name='任务')),
            ],
            options={
                'verbose_name': '采集运行记录',
                'verbose_name_plural': '采集运行记录',
                'ordering': ('task', '-run_number'),
                'constraints': [models.UniqueConstraint(fields=('task', 'run_number'), name='uniq_collection_task_run')],
            },
        ),
    ]
