# Generated by Django 5.2.16 on 2026-08-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrun',
            name='duplicate_records',
            field=models.PositiveIntegerField(default=0, verbose_name='重复记录'),
        ),
        migrations.AddField(
            model_name='collectionrun',
            name='known_threads',
            field=models.PositiveIntegerField(default=0, verbose_name='已知帖子'),
        ),
        migrations.AddField(
            model_name='collectionrun',
            name='new_records',
            field=models.PositiveIntegerField(default=0, verbose_name='新增记录'),
        ),
        migrations.AddField(
            model_name='collectionrun',
            name='new_threads',
            field=models.PositiveIntegerField(default=0, verbose_name='新增帖子'),
        ),
        migrations.AddField(
            model_name='collectionrun',
            name='stopped_at_known_boundary',
            field=models.BooleanField(default=False, verbose_name='在已知边界停止'),
        ),
        migrations.AddField(
            model_name='collectiontask',
            name='duplicate_records',
            field=models.PositiveIntegerField(default=0, verbose_name='重复记录'),
        ),
        migrations.AddField(
            model_name='collectiontask',
            name='known_threads',
            field=models.PositiveIntegerField(default=0, verbose_name='已知帖子'),
        ),
        migrations.AddField(
            model_name='collectiontask',
            name='new_records',
            field=models.PositiveIntegerField(default=0, verbose_name='新增记录'),
        ),
        migrations.AddField(
            model_name='collectiontask',
            name='new_threads',
            field=models.PositiveIntegerField(default=0, verbose_name='新增帖子'),
        ),
        migrations.AddField(
            model_name='collectiontask',
            name='stopped_at_known_boundary',
            field=models.BooleanField(default=False, verbose_name='在已知边界停止'),
        ),
    ]
