# Generated by Django 5.2.16 on 2026-07-30 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='编码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('source_type', models.CharField(choices=[('ECOMMERCE', '电商'), ('COMMUNITY', '社区')], max_length=20, verbose_name='来源类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '数据来源',
                'verbose_name_plural': '数据来源',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SourceTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=150, verbose_name='名称')),
                ('target_type', models.CharField(choices=[('PRODUCT', '商品'), ('COMMUNITY', '社区入口')], max_length=20, verbose_name='入口类型')),
                ('target_url', models.URLField(blank=True, max_length=1000, verbose_name='目标网址')),
                ('external_id', models.CharField(blank=True, max_length=200, verbose_name='外部标识')),
                ('config_json', models.JSONField(blank=True, default=dict, verbose_name='入口配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_targets', to='products.product', verbose_name='产品')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='sources.datasource', verbose_name='来源')),
            ],
            options={
                'verbose_name': '采集入口',
                'verbose_name_plural': '采集入口',
                'ordering': ('source', 'name'),
                'constraints': [models.UniqueConstraint(fields=('source', 'name'), name='uniq_source_target_name')],
            },
        ),
    ]
