# Generated by Django 5.2.16 on 2026-07-30 14:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('PENDING', '待分析'), ('SUCCESS', '成功'), ('FAILED', '失败')], default='PENDING', max_length=20, verbose_name='状态')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('model_version', models.CharField(max_length=100, verbose_name='模型版本')),
                ('prompt_version', models.CharField(max_length=100, verbose_name='Prompt 版本')),
                ('is_valid_content', models.BooleanField(default=False, verbose_name='有效内容')),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='置信度')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('raw_result', models.JSONField(blank=True, default=dict, verbose_name='原始结果')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='分析时间')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='reviews.reviewrecord', verbose_name='反馈')),
            ],
            options={
                'verbose_name': '分析结果',
                'verbose_name_plural': '分析结果',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AspectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect', models.CharField(choices=[('BATTERY', '续航'), ('CHARGING', '充电'), ('HEATING', '发热'), ('SIGNAL', '信号'), ('PERFORMANCE', '性能'), ('SYSTEM_FLUENCY', '系统流畅度'), ('SYSTEM_BUG', '系统问题'), ('DISPLAY', '屏幕'), ('CAMERA', '影像'), ('WEIGHT_AND_FEEL', '重量与手感'), ('BUILD_QUALITY', '做工'), ('AUDIO_AND_CALL', '音频与通话'), ('DURABILITY', '耐用性'), ('VALUE_FOR_MONEY', '性价比'), ('AFTER_SALES', '售后')], max_length=30, verbose_name='维度')),
                ('sentiment', models.CharField(choices=[('POSITIVE', '正面'), ('NEUTRAL', '中性'), ('NEGATIVE', '负面'), ('MIXED', '混合')], max_length=20, verbose_name='情感')),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)], verbose_name='情感分')),
                ('issue_category', models.CharField(blank=True, max_length=100, verbose_name='问题分类')),
                ('issue_summary', models.CharField(blank=True, max_length=500, verbose_name='问题摘要')),
                ('usage_scenario', models.CharField(blank=True, max_length=200, verbose_name='使用场景')),
                ('evidence_text', models.TextField(verbose_name='证据片段')),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='置信度')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspects', to='analysis.analysisresult', verbose_name='分析')),
            ],
            options={
                'verbose_name': '维度分析结果',
                'verbose_name_plural': '维度分析结果',
                'ordering': ('analysis', 'aspect'),
            },
        ),
        migrations.AddConstraint(
            model_name='analysisresult',
            constraint=models.UniqueConstraint(fields=('review', 'model_name', 'model_version', 'prompt_version'), name='uniq_review_analysis_version'),
        ),
    ]
