# Generated by Django 5.2.16 on 2026-08-08 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('products', '0002_seed_initial_products'),
        ('reviews', '0003_add_data_governance'),
        ('sources', '0005_expand_honor_phase4_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('corpus_version', models.CharField(max_length=80, verbose_name='语料版本')),
                ('provider', models.CharField(max_length=80, verbose_name='Provider')),
                ('model_name', models.CharField(max_length=150, verbose_name='模型名称')),
                ('prompt_version', models.CharField(max_length=100, verbose_name='Prompt 版本')),
                ('status', models.CharField(choices=[('PENDING', '待执行'), ('RUNNING', '执行中'), ('SUCCESS', '成功'), ('PARTIAL', '部分成功'), ('FAILED', '失败'), ('CANCELLED', '已取消')], default='PENDING', max_length=20, verbose_name='状态')),
                ('requested_count', models.PositiveIntegerField(default=0, verbose_name='计划数量')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='成功数量')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='失败数量')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='跳过数量')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='重试数量')),
                ('prompt_tokens', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Prompt Tokens')),
                ('completion_tokens', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Completion Tokens')),
                ('total_tokens', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Total Tokens')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('error_message', models.TextField(blank=True, verbose_name='安全错误信息')),
            ],
            options={
                'verbose_name': 'AI 分析批次',
                'verbose_name_plural': 'AI 分析批次',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AnalysisEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('aspect_correct', models.BooleanField(verbose_name='维度正确')),
                ('sentiment_correct', models.BooleanField(verbose_name='情感正确')),
                ('issue_correct', models.BooleanField(verbose_name='问题正确')),
                ('scenario_correct', models.BooleanField(verbose_name='场景正确')),
                ('evidence_correct', models.BooleanField(verbose_name='证据正确')),
                ('hallucination', models.BooleanField(default=False, verbose_name='存在严重幻觉')),
                ('reviewer_notes', models.TextField(blank=True, verbose_name='审核备注')),
                ('evaluated_at', models.DateTimeField(verbose_name='审核时间')),
            ],
            options={
                'verbose_name': 'AI 分析人工评估',
                'verbose_name_plural': 'AI 分析人工评估',
                'ordering': ('-evaluated_at',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='analysisresult',
            name='uniq_review_analysis_version',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0, verbose_name='调用次数'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='completion_tokens',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Completion Tokens'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='corpus_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='reviews.analysiscorpusitem', verbose_name='分析语料'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='error_code',
            field=models.CharField(blank=True, db_index=True, max_length=80, verbose_name='错误编码'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='安全错误信息'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='input_hash',
            field=models.CharField(db_index=True, default='', max_length=64, verbose_name='输入指纹'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='latency_ms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='耗时毫秒'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='prompt_tokens',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Prompt Tokens'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='provider',
            field=models.CharField(default='', max_length=80, verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='provider_request_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='Provider Request ID'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, verbose_name='重试次数'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='total_tokens',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Tokens'),
        ),
        migrations.AddField(
            model_name='aspectresult',
            name='context_dependent',
            field=models.BooleanField(default=False, verbose_name='依赖上下文'),
        ),
        migrations.AddField(
            model_name='aspectresult',
            name='context_evidence_review_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='上下文证据记录 ID'),
        ),
        migrations.AddField(
            model_name='aspectresult',
            name='context_evidence_text',
            field=models.TextField(blank=True, verbose_name='上下文证据'),
        ),
        migrations.AddField(
            model_name='analysisbatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_batches', to='products.product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='analysisbatch',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_batches', to='sources.datasource', verbose_name='来源'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='analysis.analysisbatch', verbose_name='分析批次'),
        ),
        migrations.AddConstraint(
            model_name='analysisresult',
            constraint=models.UniqueConstraint(fields=('review', 'provider', 'model_name', 'prompt_version', 'input_hash'), name='uniq_review_analysis_input'),
        ),
        migrations.AddField(
            model_name='analysisevaluation',
            name='analysis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='analysis.analysisresult', verbose_name='分析结果'),
        ),
    ]
