# Generated by Django 5.2.16 on 2026-07-30 14:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='外部标识')),
                ('parent_external_id', models.CharField(blank=True, max_length=255, verbose_name='父记录外部标识')),
                ('record_type', models.CharField(choices=[('REVIEW', '评价'), ('APPEND_REVIEW', '追评'), ('THREAD', '帖子'), ('REPLY', '回复'), ('OFFICIAL_REPLY', '官方回复')], max_length=30, verbose_name='记录类型')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='评分')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('software_version', models.CharField(blank=True, max_length=100, verbose_name='软件版本')),
                ('author_role', models.CharField(choices=[('USER', '用户'), ('OFFICIAL', '官方'), ('UNKNOWN', '未知')], default='UNKNOWN', max_length=20, verbose_name='作者角色')),
                ('is_official', models.BooleanField(default=False, verbose_name='官方内容')),
                ('is_append_review', models.BooleanField(default=False, verbose_name='追评')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='来源网址')),
                ('content_hash', models.CharField(db_index=True, max_length=64, verbose_name='内容指纹')),
                ('raw_data', models.JSONField(default=dict, verbose_name='原始数据')),
                ('status', models.CharField(choices=[('RAW', '原始'), ('NORMALIZED', '已标准化'), ('INVALID', '无效')], default='RAW', max_length=20, verbose_name='处理状态')),
                ('collected_at', models.DateTimeField(verbose_name='采集时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='products.product', verbose_name='产品')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='products.productvariant', verbose_name='产品版本')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='sources.datasource', verbose_name='来源')),
                ('source_target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='sources.sourcetarget', verbose_name='采集入口')),
            ],
            options={
                'verbose_name': '反馈记录',
                'verbose_name_plural': '反馈记录',
                'ordering': ('-published_at', '-created_at'),
                'indexes': [models.Index(fields=['source', 'record_type', 'published_at'], name='review_source_type_time'), models.Index(fields=['product', 'published_at'], name='review_product_time')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id__isnull', False), models.Q(('external_id', ''), _negated=True)), fields=('source', 'external_id', 'record_type'), name='uniq_review_source_external_type')],
            },
        ),
    ]
