# Generated by Django 5.2.16 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewrecord",
            name="author_role",
            field=models.CharField(
                choices=[
                    ("USER", "用户"),
                    ("OFFICIAL", "官方"),
                    ("MODERATOR", "版主"),
                    ("EXPERT", "达人"),
                    ("UNKNOWN", "未知"),
                ],
                default="UNKNOWN",
                max_length=20,
                verbose_name="作者角色",
            ),
        ),
    ]
