# Generated by Django 5.2.16 on 2026-08-07 23:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_seed_initial_products'),
        ('reviews', '0002_expand_author_roles'),
        ('sources', '0004_source_product_variant_and_jd_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('normalized_text', models.TextField(blank=True, verbose_name='标准化文本')),
                ('has_meaningful_text', models.BooleanField(default=False, verbose_name='包含有效文本')),
                ('is_product_related', models.BooleanField(default=False, verbose_name='产品相关')),
                ('is_official_content', models.BooleanField(default=False, verbose_name='官方内容')),
                ('is_low_information', models.BooleanField(default=False, verbose_name='低信息')),
                ('is_navigation_or_page_noise', models.BooleanField(default=False, verbose_name='页面噪声')),
                ('is_promotional', models.BooleanField(default=False, verbose_name='宣传内容')),
                ('is_duplicate', models.BooleanField(default=False, verbose_name='重复')),
                ('eligible_for_ai', models.BooleanField(db_index=True, default=False, verbose_name='AI 语料可用')),
                ('exclusion_reason', models.CharField(choices=[('NONE', '不排除'), ('EMPTY_CONTENT', '空内容'), ('OFFICIAL_CONTENT', '官方内容'), ('PRODUCT_NOT_MATCHED', '产品不相关'), ('PAGE_NOISE', '页面噪声'), ('PROMOTIONAL', '宣传内容'), ('LOW_INFORMATION', '低信息'), ('DUPLICATE', '重复'), ('INVALID_ENCODING', '无效编码'), ('PARSER_ARTIFACT', '解析残留'), ('OTHER', '其他')], db_index=True, default='NONE', max_length=30, verbose_name='排除原因')),
                ('quality_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='语料质量分')),
                ('flags_json', models.JSONField(blank=True, default=dict, verbose_name='规则标记')),
                ('processor_version', models.CharField(db_index=True, max_length=50, verbose_name='处理器版本')),
                ('processed_at', models.DateTimeField(verbose_name='处理时间')),
                ('manual_override', models.BooleanField(default=False, verbose_name='人工覆盖')),
                ('manual_eligible', models.BooleanField(blank=True, null=True, verbose_name='人工可用判断')),
                ('manual_reason', models.TextField(blank=True, verbose_name='人工覆盖原因')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_quality_records', to='reviews.reviewrecord', verbose_name='重复于')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality', to='reviews.reviewrecord', verbose_name='反馈记录')),
            ],
            options={
                'verbose_name': '反馈数据质量',
                'verbose_name_plural': '反馈数据质量',
                'ordering': ('-processed_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AnalysisCorpusItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('record_type', models.CharField(choices=[('REVIEW', '评价'), ('APPEND_REVIEW', '追评'), ('THREAD', '帖子'), ('REPLY', '回复'), ('OFFICIAL_REPLY', '官方回复')], max_length=30, verbose_name='记录类型')),
                ('author_role', models.CharField(choices=[('USER', '用户'), ('OFFICIAL', '官方'), ('MODERATOR', '版主'), ('EXPERT', '达人'), ('UNKNOWN', '未知')], max_length=20, verbose_name='作者角色')),
                ('normalized_text', models.TextField(blank=True, verbose_name='标准化文本')),
                ('context_text', models.TextField(blank=True, verbose_name='分析上下文')),
                ('eligible', models.BooleanField(db_index=True, default=False, verbose_name='可用于 AI')),
                ('exclusion_reason', models.CharField(choices=[('NONE', '不排除'), ('EMPTY_CONTENT', '空内容'), ('OFFICIAL_CONTENT', '官方内容'), ('PRODUCT_NOT_MATCHED', '产品不相关'), ('PAGE_NOISE', '页面噪声'), ('PROMOTIONAL', '宣传内容'), ('LOW_INFORMATION', '低信息'), ('DUPLICATE', '重复'), ('INVALID_ENCODING', '无效编码'), ('PARSER_ARTIFACT', '解析残留'), ('OTHER', '其他')], db_index=True, default='NONE', max_length=30, verbose_name='排除原因')),
                ('quality_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='语料质量分')),
                ('corpus_version', models.CharField(db_index=True, max_length=80, verbose_name='语料版本')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corpus_items', to='products.product', verbose_name='产品')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corpus_item', to='reviews.reviewrecord', verbose_name='反馈记录')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corpus_items', to='sources.datasource', verbose_name='来源')),
                ('quality', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corpus_item', to='reviews.reviewquality', verbose_name='治理结果')),
            ],
            options={
                'verbose_name': 'AI 分析语料',
                'verbose_name_plural': 'AI 分析语料',
                'ordering': ('review_id',),
            },
        ),
        migrations.CreateModel(
            name='ReviewQualityRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('processor_version', models.CharField(max_length=50, verbose_name='处理器版本')),
                ('normalized_text', models.TextField(blank=True, verbose_name='标准化文本')),
                ('eligible_for_ai', models.BooleanField(default=False, verbose_name='AI 语料可用')),
                ('exclusion_reason', models.CharField(choices=[('NONE', '不排除'), ('EMPTY_CONTENT', '空内容'), ('OFFICIAL_CONTENT', '官方内容'), ('PRODUCT_NOT_MATCHED', '产品不相关'), ('PAGE_NOISE', '页面噪声'), ('PROMOTIONAL', '宣传内容'), ('LOW_INFORMATION', '低信息'), ('DUPLICATE', '重复'), ('INVALID_ENCODING', '无效编码'), ('PARSER_ARTIFACT', '解析残留'), ('OTHER', '其他')], default='NONE', max_length=30, verbose_name='排除原因')),
                ('quality_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='语料质量分')),
                ('flags_json', models.JSONField(blank=True, default=dict, verbose_name='规则标记')),
                ('processed_at', models.DateTimeField(verbose_name='处理时间')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_runs', to='reviews.reviewrecord', verbose_name='反馈记录')),
            ],
            options={
                'verbose_name': '反馈治理版本记录',
                'verbose_name_plural': '反馈治理版本记录',
                'ordering': ('review_id', '-processed_at'),
            },
        ),
        migrations.AddIndex(
            model_name='reviewquality',
            index=models.Index(fields=['exclusion_reason', 'quality_score'], name='quality_reason_score'),
        ),
        migrations.AddIndex(
            model_name='reviewquality',
            index=models.Index(fields=['processor_version', 'eligible_for_ai'], name='quality_version_eligible'),
        ),
        migrations.AddIndex(
            model_name='analysiscorpusitem',
            index=models.Index(fields=['product', 'corpus_version', 'eligible'], name='corpus_product_version'),
        ),
        migrations.AddIndex(
            model_name='analysiscorpusitem',
            index=models.Index(fields=['source', 'record_type', 'eligible'], name='corpus_source_type'),
        ),
        migrations.AddConstraint(
            model_name='reviewqualityrun',
            constraint=models.UniqueConstraint(fields=('review', 'processor_version'), name='uniq_quality_run_review_version'),
        ),
    ]
