# Generated by Django 5.2.16 on 2026-07-30 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('period_start', models.DateTimeField(verbose_name='统计开始时间')),
                ('period_end', models.DateTimeField(verbose_name='统计结束时间')),
                ('status', models.CharField(choices=[('PENDING', '待生成'), ('READY', '已生成'), ('FAILED', '失败')], default='PENDING', max_length=20, verbose_name='状态')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='报告快照')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='products.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '聚合报告',
                'verbose_name_plural': '聚合报告',
                'ordering': ('-period_end',),
            },
        ),
    ]
