# Generated by Django 5.2.16 on 2026-07-30 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='编码')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=150, verbose_name='名称')),
                ('normalized_name', models.CharField(max_length=150, unique=True, verbose_name='标准名称')),
                ('series', models.CharField(max_length=100, verbose_name='系列')),
                ('model_code', models.CharField(blank=True, max_length=100, verbose_name='型号编码')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.brand', verbose_name='品牌')),
            ],
            options={
                'verbose_name': '手机产品',
                'verbose_name_plural': '手机产品',
                'ordering': ('brand__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('alias', models.CharField(max_length=150, verbose_name='别名')),
                ('normalized_alias', models.CharField(max_length=150, verbose_name='标准化别名')),
                ('source', models.CharField(blank=True, max_length=50, verbose_name='别名来源')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='products.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品别名',
                'verbose_name_plural': '产品别名',
                'ordering': ('alias',),
                'constraints': [models.UniqueConstraint(fields=('product', 'normalized_alias'), name='uniq_product_normalized_alias')],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('memory', models.CharField(max_length=30, verbose_name='内存')),
                ('storage', models.CharField(max_length=30, verbose_name='存储')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='颜色')),
                ('sku_name', models.CharField(max_length=150, verbose_name='SKU 名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品版本',
                'verbose_name_plural': '产品版本',
                'ordering': ('product', 'memory', 'storage', 'color'),
                'constraints': [models.UniqueConstraint(fields=('product', 'memory', 'storage', 'color'), name='uniq_product_variant_spec')],
            },
        ),
    ]
